# Generated by Django 5.2 on 2025-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.PositiveBigIntegerField()),
                ('digital', models.PositiveBigIntegerField()),
                ('credit', models.PositiveBigIntegerField()),
                ('description', models.TextField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invesments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('stock', 'stock'), ('VFF', 'VFF'), ('VMEEF', 'VMEEF'), ('DCDE', 'DCDE'), ('VESAF', 'VESAF'), ('VEOF', 'VEOF'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=10)),
                ('amount', models.PositiveBigIntegerField()),
            ],
        ),
    ]
